### ISSUE TITLE
transformer中添加注意力的过程可能造成答案泄露问题

### ISSUE THREAD

**Issue by W1Fl** [MorvanZhou/NLP-Tutorials#10]
你好，
我注意到了encoder这一段代码
 ```    def call(self, yz, xz, training, look_ahead_mask, pad_mask):
        attn = self.mh[0].call(yz, yz, yz, look_ahead_mask, training)       # decoder self attention
        o1 = self.bn[0](attn + yz, training)
        attn = self.mh[1].call(o1, xz, xz, pad_mask, training)       # decoder + encoder attention
        o2 = self.bn[1](attn + o1, training)
        ffn = self.drop(self.ffn.call(o2), training)
        o = self.bn[2](ffn + o2, training)
        return o 
```

其中， `o1 = self.bn[0](attn + yz, training) `  可能产生了训练和推理操作不统一的问题（推理输出依赖标签）
比如，在我的实验中，我更改标签第二位（Go标记后一位）的值使得推理结果第二位（Go标记后一位）结果发生改变，这使得训练准确度跟测试准确度有很大的差异。
是否应该为这一步的yz添加mask或者去掉这个操作避免这种影响。

**Comment by MorvanZhou** [comment]
推理的时候，你应该是指的`translate()`这个功能吧？我对这句话做一下解释：“在我的实验中，我更改标签第二位（Go标记后一位）的值使得推理结果第二位（Go标记后一位）结果发生改变”

input的第二位假设是X2, 那么对应output的Y2输出的是下一位X3位置的值，所以更改X2,Y2会有变化，因为Y2->X3

**Comment by W1Fl** [comment]
我是指训练过程，推理过程中标签是初始化为go的

**Comment by MorvanZhou** [comment]
训练过程也是从`<GO>`开始的呀，
```
bx, by, seq_len = data.sample(64)
```
这里sample出来的`by`最开始一位都是 14 `<GO>`

**Comment by MorvanZhou** [comment]
> 我是指训练过程，推理过程中标签是初始化为go的

另外，我最近又commit了一些代码，比如你代码中的bn，我换成了layerNorm

**Comment by MorvanZhou** [comment]
@W1Fl 关于代码转写，如果想在微信上聊，你可以发一个email给我 morvanzhou@hotmail.com

**Comment by MorvanZhou** [comment]
确认了，这的确是一个问题，是layernormstep维度上的信息，使得inference step信息变化时，预测也随之变化。已修复
