### ISSUE TITLE
visual.py文件下的show_tfidf存在问题

### ISSUE THREAD

**Issue by meraks** [MorvanZhou/NLP-Tutorials#12]
def show_tfidf(tfidf, vocb, filename):
    # [n_vocab, n_doc]
    plt.imshow(tfidf, cmap="YlGn", vmin=tfidf.min(), vmax=tfidf.max())
    plt.xticks(np.arange(tfidf.shape[1]+1), vocb, fontsize=6, rotation=90)
    plt.yticks(np.arange(tfidf.shape[0]), np.arange(1, tfidf.shape[0] + 1), fontsize=6)
    plt.tight_layout()
    plt.savefig("./visual/results/%s.png" % filename, format="png", dpi=500)
    plt.show()

原始的plt.xticks和plt.yticks有一点点小问题，经修改后可以解决问题。

**Comment by MorvanZhou** [comment]
恩，画图里有些问题，输出vocab的时候也有点问题，应为引入了在预测是的新词汇。我修改了重推
