### ISSUE TITLE
在tf-idf的numpy计算tf中有些问题想请教一下

### ISSUE THREAD

**Issue by SuperLiuYinXin** [MorvanZhou/NLP-Tutorials#13]
tf的计算公式的词出现的频率/文档中词的总个数.  为什么在代码中除的是出现最多的单词个数.
这里有些困惑

**Comment by MorvanZhou** [comment]
tf的计算方法有很多种，针对不同的文档属性，可以尝试不同的公式，看看哪一种能够达到更好的效果。如果文档量多，而且词频稀疏，那么除以文档词总个数就会让词语没有区分力。
