### ISSUE TITLE
BERT problem

### ISSUE THREAD

**Issue by chriswang0122** [MorvanZhou/NLP-Tutorials#14]
Thanks for the tutorials.

Your implementation of BERT is different from the original parer.
You use all tokens for NSP(next sentence prediction) instead of "[CLS]" token.

https://github.com/MorvanZhou/NLP-Tutorials/blob/master/GPT.py
```
def call(self, seqs, segs, training=False):
        embed = self.input_emb(seqs, segs)  # [n, step, dim]
        z = self.encoder(embed, training=training, mask=self.mask(seqs))     # [n, step, dim]
        mlm_logits = self.task_mlm(z)  # [n, step, n_vocab]
        nsp_logits = self.task_nsp(tf.reshape(z, [z.shape[0], -1]))  # [n, n_cls]
        return mlm_logits, nsp_logits
```

It seems to me that this should be changed as below
```
def call(self, seqs, segs, training=False):
        embed = self.input_emb(seqs, segs)  # [n, step, dim]
        z = self.encoder(embed, training=training, mask=self.mask(seqs))     # [n, step, dim]
        mlm_logits = self.task_mlm(z)  # [n, step, n_vocab]
        nsp_logits = self.task_nsp(tf.reshape(z[:, 0,:], [z.shape[0], -1]))  # [n, n_cls]
        return mlm_logits, nsp_logits
```

There are some reimplementations following the tutorials with PyTorch.
- [ELMo](https://github.com/chriswang0122/100-Days-of-NLP-Marathon/blob/master/Deep%20Learning/D28%20NLP%20ELMo%20%E9%A0%90%E8%A8%93%E7%B7%B4%E6%A8%A1%E5%9E%8B%E4%BB%8B%E7%B4%B9%E8%88%87%E7%AF%84%E4%BE%8B%E5%AF%A6%E4%BD%9C/CH28_%E4%BD%9C%E6%A5%AD.ipynb)
- [BERT](https://github.com/chriswang0122/100-Days-of-NLP-Marathon/blob/master/Deep%20Learning/D29%20Transformer%EF%BC%8B%E9%A0%90%E8%A8%93%E7%B7%B4%EF%BC%9A%E9%9B%86%E5%A4%A7%E6%88%90%E7%9A%84%20Bert%20%E6%A8%A1%E5%9E%8B/CH29_%E4%BD%9C%E6%A5%AD.ipynb)

Hope them help the people who are not be good at TensorFlow.

**Comment by MorvanZhou** [comment]
Yes, I made them different on purpose. Explanation in here https://github.com/MorvanZhou/NLP-Tutorials/blob/master/BERT.py#L14-L18
