### ISSUE TITLE
pytorch seq2seq 报错

### ISSUE THREAD

**Issue by 719676340** [MorvanZhou/NLP-Tutorials#20]
在pytorch版本的seq2seq 的81行会出现
expected scalar type Long but found Int
问题

**Comment by MorvanZhou** [comment]
代码是@ruifan831 @ruifanxu 开源贡献的，作者来看看是什么问题吧

**Comment by ruifan831** [comment]
> 在pytorch版本的seq2seq 的81行会出现
> expected scalar type Long but found Int
> 问题

我在我这电脑上并没有出现 你这样的问题。
你可以试试在96行后添加以下代码试试
 ```
bx = bx.type(torch.LongTensor)
by = by.type(torch.LongTensor)
```

**Comment by 719676340** [comment]
> > 在pytorch版本的seq2seq 的81行会出现
> > expected scalar type Long but found Int
> > 问题
> 
> 我在我这电脑上并没有出现 你这样的问题。
> 你可以试试在96行后添加以下代码试试
> 
> ```
> bx = bx.type(torch.LongTensor)
> by = by.type(torch.LongTensor)
> ```

问题解决了  感谢
