### ISSUE TITLE
关于visual.py中show_tfidf函数报错问题（Problems about 'show_tfidf' function in visual.py）

### ISSUE THREAD

**Issue by Taylor-Swift1** [MorvanZhou/NLP-Tutorials#26]
plt.savefig("./visual/results/%s.png" % filename, format="png", dpi=500)
执行到这一行报错"No Such File or Direction"

**解决方案：**
将源代码替换为如下代码
    # creating the output folder 
    output_folder = './visual/'
    if not os.path.exists(output_folder):
       os.makedirs(output_folder)
    plt.savefig(os.path.join(output_folder, '%s.png') % filename, format="png", dpi=500)

本想pull request一下，没想到竟然不会，所以只能这么low的在这发个issues，刚入门NLP，很感谢作者的开源教程，希望越来越好

**### English Version：**
plt.savefig("./visual/results/%s.png" % filename, format="png", dpi=500)
While excuting this line, it encouters problem: No Such File or Direction.

**Solution:**
replace the original code as below:
    # creating the output folder 
    output_folder = './visual/'
    if not os.path.exists(output_folder):
       os.makedirs(output_folder)
    plt.savefig(os.path.join(output_folder, '%s.png') % filename, format="png", dpi=500)

I began to learn NLP several days ago. Thanks for the author's opened tutorrial video. I hope that author's video will be known by more people.

**Comment by MorvanZhou** [comment]
PR has been accepted
