### ISSUE TITLE
运行skip-gram报错

### ISSUE THREAD

**Issue by lu776** [MorvanZhou/NLP-Tutorials#3]
File "D:/Desktop/Information-Extraction-Chinese-master/skip-gram.py", line 79
    _loss: tf.Tensor = self.loss(x, y, True)
         ^
SyntaxError: invalid syntax

Process finished with exit code 1
请求解答，十分感谢。

**Comment by MorvanZhou** [comment]
可能是应为Python的版本没有办法解析 `_loss: tf.Tensor `这个语句，可以把它改成 `_loss = self.loss(x, y, True)`. 我也重新push 一下

commit: https://github.com/MorvanZhou/NLP-Tutorials/commit/c14feb75b74fbad4bf8ef3050248882c8af7baa1

**Comment by MorvanZhou** [comment]
https://github.com/MorvanZhou/NLP-Tutorials/commit/c14feb75b74fbad4bf8ef3050248882c8af7baa1
