### ISSUE TITLE
transformer一些组件和原文不一致

### ISSUE THREAD

**Issue by W1Fl** [MorvanZhou/NLP-Tutorials#7]
你好
1. 文中q,k,v由矩阵乘法计算而来,代码中为全连接层
2. 文中使用LayerNormalization,代码中为BatchNormalization

这样会对效果造成影响吗

**Comment by MorvanZhou** [comment]
1. 全连接其实就是矩阵乘
2. 这个也没有特别的解释，可以参考一下这里 https://zhuanlan.zhihu.com/p/126749311 。 我还是把 BN改成LN好了。哈哈
